/*
 * Object
 *
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.object.admin.rest.client', and version '1.0.45'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Facet {
    #[serde(rename = "facetCriteria", skip_serializing_if = "Option::is_none")]
    pub facet_criteria: Option<String>,
    #[serde(rename = "facetValues", skip_serializing_if = "Option::is_none")]
    pub facet_values: Option<Vec<crate::models::FacetValue>>,
}

impl Facet {
    pub fn new() -> Facet {
        Facet {
            facet_criteria: None,
            facet_values: None,
        }
    }
}


