/*
 * Object
 *
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.object.admin.rest.client', and version '1.0.45'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FacetValue {
    #[serde(rename = "numberOfOccurrences", skip_serializing_if = "Option::is_none")]
    pub number_of_occurrences: Option<i32>,
    #[serde(rename = "term", skip_serializing_if = "Option::is_none")]
    pub term: Option<String>,
}

impl FacetValue {
    pub fn new() -> FacetValue {
        FacetValue {
            number_of_occurrences: None,
            term: None,
        }
    }
}


