/*
 * Object
 *
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.object.admin.rest.client', and version '1.0.45'.
 *
 * The version of the OpenAPI document: v1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use headless_common::convert_case::Casing;
use headless_common::{convert_case::Case, field_types::FieldName};
use std::fmt::Display;

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, FieldName)]
pub struct ObjectAction {
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions:
        Option<::std::collections::HashMap<String, ::std::collections::HashMap<String, String>>>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(
        rename = "conditionExpression",
        skip_serializing_if = "Option::is_none"
    )]
    pub condition_expression: Option<String>,
    #[serde(rename = "dateCreated", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    #[serde(rename = "dateModified", skip_serializing_if = "Option::is_none")]
    pub date_modified: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<::std::collections::HashMap<String, String>>,
    #[serde(
        rename = "externalReferenceCode",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_reference_code: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(
        rename = "objectActionExecutorKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub object_action_executor_key: Option<String>,
    #[serde(
        rename = "objectActionTriggerKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub object_action_trigger_key: Option<String>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<::std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::Status>>,
    #[serde(rename = "x-class-name", skip_serializing_if = "Option::is_none")]
    pub x_class_name: Option<String>,
}

impl Display for ObjectActionFieldName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.name().to_case(Case::Camel))
    }
}

pub use ObjectActionFieldName as ObjectActionField;

impl ObjectAction {
    pub fn new() -> ObjectAction {
        ObjectAction {
            actions: None,
            active: None,
            condition_expression: None,
            date_created: None,
            date_modified: None,
            description: None,
            error_message: None,
            external_reference_code: None,
            id: None,
            label: None,
            name: None,
            object_action_executor_key: None,
            object_action_trigger_key: None,
            parameters: None,
            status: None,
            x_class_name: None,
        }
    }
}
