/*
 * Object
 *
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.object.admin.rest.client', and version '1.0.45'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ObjectView {
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<::std::collections::HashMap<String, ::std::collections::HashMap<String, String>>>,
    #[serde(rename = "dateCreated", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    #[serde(rename = "dateModified", skip_serializing_if = "Option::is_none")]
    pub date_modified: Option<String>,
    #[serde(rename = "defaultObjectView", skip_serializing_if = "Option::is_none")]
    pub default_object_view: Option<bool>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "objectDefinitionExternalReferenceCode", skip_serializing_if = "Option::is_none")]
    pub object_definition_external_reference_code: Option<String>,
    #[serde(rename = "objectDefinitionId", skip_serializing_if = "Option::is_none")]
    pub object_definition_id: Option<i64>,
    #[serde(rename = "objectViewColumns", skip_serializing_if = "Option::is_none")]
    pub object_view_columns: Option<Vec<crate::models::ObjectViewColumn>>,
    #[serde(rename = "objectViewFilterColumns", skip_serializing_if = "Option::is_none")]
    pub object_view_filter_columns: Option<Vec<crate::models::ObjectViewFilterColumn>>,
    #[serde(rename = "objectViewSortColumns", skip_serializing_if = "Option::is_none")]
    pub object_view_sort_columns: Option<Vec<crate::models::ObjectViewSortColumn>>,
    #[serde(rename = "x-class-name", skip_serializing_if = "Option::is_none")]
    pub x_class_name: Option<String>,
}

impl ObjectView {
    pub fn new() -> ObjectView {
        ObjectView {
            actions: None,
            date_created: None,
            date_modified: None,
            default_object_view: None,
            id: None,
            name: None,
            object_definition_external_reference_code: None,
            object_definition_id: None,
            object_view_columns: None,
            object_view_filter_columns: None,
            object_view_sort_columns: None,
            x_class_name: None,
        }
    }
}


