/*
 * Object
 *
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.object.admin.rest.client', and version '1.0.45'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ObjectLayoutBox {
    #[serde(rename = "collapsable", skip_serializing_if = "Option::is_none")]
    pub collapsable: Option<bool>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "objectLayoutRows", skip_serializing_if = "Option::is_none")]
    pub object_layout_rows: Option<Vec<crate::models::ObjectLayoutRow>>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<RHashType>,
    #[serde(rename = "x-class-name", skip_serializing_if = "Option::is_none")]
    pub x_class_name: Option<String>,
}

impl ObjectLayoutBox {
    pub fn new() -> ObjectLayoutBox {
        ObjectLayoutBox {
            collapsable: None,
            id: None,
            name: None,
            object_layout_rows: None,
            priority: None,
            r#type: None,
            x_class_name: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "categorization")]
    Categorization,
    #[serde(rename = "regular")]
    Regular,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Categorization
    }
}

