/*
 * Object
 *
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.object.admin.rest.client', and version '1.0.45'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ObjectLayoutTab {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "objectLayoutBoxes", skip_serializing_if = "Option::is_none")]
    pub object_layout_boxes: Option<Vec<crate::models::ObjectLayoutBox>>,
    #[serde(rename = "objectRelationshipId", skip_serializing_if = "Option::is_none")]
    pub object_relationship_id: Option<i64>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    #[serde(rename = "x-class-name", skip_serializing_if = "Option::is_none")]
    pub x_class_name: Option<String>,
}

impl ObjectLayoutTab {
    pub fn new() -> ObjectLayoutTab {
        ObjectLayoutTab {
            id: None,
            name: None,
            object_layout_boxes: None,
            object_relationship_id: None,
            priority: None,
            x_class_name: None,
        }
    }
}


