openapi: 3.0.1
info:
  title: Headless Batch Engine
  description: A Java client JAR is available for use with the group ID 'com.liferay',
    artifact ID 'com.liferay.headless.batch.engine.client', and version '1.0.11'.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1.0
servers:
- url: http://localhost:8080/o/headless-batch-engine/
paths:
  /v1.0/export-task/{exportTaskId}:
    get:
      tags:
      - ExportTask
      description: Retrieves the export task.
      operationId: getExportTask
      parameters:
      - name: exportTaskId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportTask'
            application/xml:
              schema:
                $ref: '#/components/schemas/ExportTask'
  /v1.0/export-task/{exportTaskId}/content:
    get:
      tags:
      - ExportTask
      description: Retrieves the exported content.
      operationId: getExportTaskContent
      parameters:
      - name: exportTaskId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/octet-stream: {}
  /v1.0/export-task/{className}/{contentType}:
    post:
      tags:
      - ExportTask
      description: Submits a request for exporting items to a file.
      operationId: postExportTask
      parameters:
      - name: className
        in: path
        required: true
        schema:
          type: string
      - name: contentType
        in: path
        required: true
        schema:
          type: string
      - name: callbackURL
        in: query
        schema:
          type: string
      - name: externalReferenceCode
        in: query
        schema:
          type: string
      - name: fieldNames
        in: query
        schema:
          type: string
      - name: taskItemDelegateName
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportTask'
            application/xml:
              schema:
                $ref: '#/components/schemas/ExportTask'
  /v1.0/export-task/by-external-reference-code/{externalReferenceCode}:
    get:
      tags:
      - ExportTask
      description: Retrieves the export task by external reference code.
      operationId: getExportTaskByExternalReferenceCode
      parameters:
      - name: externalReferenceCode
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportTask'
            application/xml:
              schema:
                $ref: '#/components/schemas/ExportTask'
  /v1.0/export-task/by-external-reference-code/{externalReferenceCode}/content:
    get:
      tags:
      - ExportTask
      description: Retrieves the exported content by external reference code.
      operationId: getExportTaskByExternalReferenceCodeContent
      parameters:
      - name: externalReferenceCode
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/octet-stream: {}
  /v1.0/import-task/by-external-reference-code/{externalReferenceCode}:
    get:
      tags:
      - ImportTask
      description: Retrieves the import task by external reference code.
      operationId: getImportTaskByExternalReferenceCode
      parameters:
      - name: externalReferenceCode
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportTask'
            application/xml:
              schema:
                $ref: '#/components/schemas/ImportTask'
  /v1.0/import-task/{importTaskId}/failed-items/report:
    get:
      tags:
      - ImportTask
      operationId: getImportTaskFailedItemReport
      parameters:
      - name: importTaskId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/octet-stream: {}
  /v1.0/import-task/{importTaskId}:
    get:
      tags:
      - ImportTask
      description: Retrieves the import task.
      operationId: getImportTask
      parameters:
      - name: importTaskId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportTask'
            application/xml:
              schema:
                $ref: '#/components/schemas/ImportTask'
  /v1.0/import-task/{importTaskId}/content:
    get:
      tags:
      - ImportTask
      description: Retrieves the exported content.
      operationId: getImportTaskContent
      parameters:
      - name: importTaskId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/octet-stream: {}
  /v1.0/import-task/{className}:
    put:
      tags:
      - ImportTask
      description: Uploads a new file for updating items in batch.
      operationId: putImportTask_1
      parameters:
      - name: className
        in: path
        required: true
        schema:
          type: string
      - name: callbackURL
        in: query
        schema:
          type: string
      - name: externalReferenceCode
        in: query
        schema:
          type: string
      - name: importStrategy
        in: query
        schema:
          type: string
      - name: taskItemDelegateName
        in: query
        schema:
          type: string
      - name: updateStrategy
        in: query
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MultipartBody'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportTask'
            application/xml:
              schema:
                $ref: '#/components/schemas/ImportTask'
    post:
      tags:
      - ImportTask
      description: Uploads a new file for creating new items in batch.
      operationId: postImportTask_1
      parameters:
      - name: className
        in: path
        required: true
        schema:
          type: string
      - name: callbackURL
        in: query
        schema:
          type: string
      - name: createStrategy
        in: query
        schema:
          type: string
      - name: externalReferenceCode
        in: query
        schema:
          type: string
      - name: fieldNameMapping
        in: query
        schema:
          type: string
      - name: importStrategy
        in: query
        schema:
          type: string
      - name: taskItemDelegateName
        in: query
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MultipartBody'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportTask'
            application/xml:
              schema:
                $ref: '#/components/schemas/ImportTask'
    delete:
      tags:
      - ImportTask
      description: Uploads a new file for deleting items in batch.
      operationId: deleteImportTask_1
      parameters:
      - name: className
        in: path
        required: true
        schema:
          type: string
      - name: callbackURL
        in: query
        schema:
          type: string
      - name: externalReferenceCode
        in: query
        schema:
          type: string
      - name: importStrategy
        in: query
        schema:
          type: string
      - name: taskItemDelegateName
        in: query
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MultipartBody'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImportTask'
            application/xml:
              schema:
                $ref: '#/components/schemas/ImportTask'
  /v1.0/import-task/by-external-reference-code/{externalReferenceCode}/content:
    get:
      tags:
      - ImportTask
      description: Retrieves the exported content by external reference code.
      operationId: getImportTaskByExternalReferenceCodeContent
      parameters:
      - name: externalReferenceCode
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/octet-stream: {}
  /v1.0/import-task/by-external-reference-code/{externalReferenceCode}/failed-items/report:
    get:
      tags:
      - ImportTask
      operationId: getImportTaskByExternalReferenceCodeFailedItemReport
      parameters:
      - name: externalReferenceCode
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/octet-stream: {}
  /v1.0/openapi.{type}:
    get:
      operationId: getOpenAPI
      parameters:
      - name: type
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
            application/yaml: {}
components:
  schemas:
    ExportTask:
      type: object
      properties:
        className:
          type: string
          description: The item class name for which data will be exported in batch.
          example: com.liferay.headless.delivery.dto.v1_0.BlogPosting
        contentType:
          type: string
          description: The file content type.
          example: JSON
        endTime:
          type: string
          description: The end time of export task operation.
          format: date-time
        errorMessage:
          type: string
          description: The error message in case of export task's failed execution.
          example: File import failed
        executeStatus:
          type: string
          description: The status of export task's execution.
          example: INITIALIZED
          enum:
          - COMPLETED
          - FAILED
          - INITIAL
          - STARTED
        externalReferenceCode:
          type: string
          description: The optional external key of this account.
        id:
          type: integer
          description: The task's ID.
          format: int64
          example: 30130
        processedItemsCount:
          type: integer
          description: Number of items processed by export task opeartion.
          format: int32
          example: 100
        startTime:
          type: string
          description: The start time of export task operation.
          format: date-time
        totalItemsCount:
          type: integer
          description: Total number of items that will be processed by export task
            operation.
          format: int32
          example: 1000
        x-class-name:
          type: string
          readOnly: true
          default: com.liferay.headless.batch.engine.dto.v1_0.ExportTask
      xml:
        name: ExportTask
    FailedItem:
      type: object
      properties:
        item:
          type: string
          description: The item which failed to be imported.
        itemIndex:
          type: integer
          description: Position of the item in the import file. For CSV file it will
            represent a line number, for JSON file it will represent an array index
            etc.
          format: int32
        message:
          type: string
          description: Message describing the reason of import failure.
        x-class-name:
          type: string
          readOnly: true
          default: com.liferay.headless.batch.engine.dto.v1_0.FailedItem
      xml:
        name: FailedItem
    ImportTask:
      type: object
      properties:
        className:
          type: string
          description: The item class name for which data will be processed in batch.
          example: com.liferay.headless.delivery.dto.v1_0.BlogPosting
        contentType:
          type: string
          description: The file content type.
          example: JSON
        endTime:
          type: string
          description: The end time of import task operation.
          format: date-time
        errorMessage:
          type: string
          description: The error message in case of import task's failed execution.
          example: File import failed
        executeStatus:
          type: string
          description: The status of import task's execution.
          example: INITIALIZED
          enum:
          - COMPLETED
          - FAILED
          - INITIAL
          - STARTED
        externalReferenceCode:
          type: string
          description: The optional external key of this account.
        failedItems:
          type: array
          items:
            $ref: '#/components/schemas/FailedItem'
        id:
          type: integer
          description: The task's ID.
          format: int64
          example: 30130
        importStrategy:
          type: string
          description: Defines if import task will fail when error occurs or continue
            importing rest of the items.
          enum:
          - ON_ERROR_CONTINUE
          - ON_ERROR_FAIL
        operation:
          type: string
          description: The operation of import task.
          example: CREATE
          enum:
          - CREATE
          - DELETE
          - UPDATE
        processedItemsCount:
          type: integer
          description: Number of items processed by import task opeartion.
          format: int32
          example: 100
        startTime:
          type: string
          description: The start time of import task operation.
          format: date-time
        totalItemsCount:
          type: integer
          description: Total number of items that will be processed by import task
            operation.
          format: int32
          example: 1000
        x-class-name:
          type: string
          readOnly: true
          default: com.liferay.headless.batch.engine.dto.v1_0.ImportTask
      xml:
        name: ImportTask
    MultipartBody:
      type: object
      properties:
        values:
          type: object
          additionalProperties:
            type: string
