/*
 * Headless Batch Engine
 *
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.headless.batch.engine.client', and version '1.0.11'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FailedItem {
    /// The item which failed to be imported.
    #[serde(rename = "item", skip_serializing_if = "Option::is_none")]
    pub item: Option<String>,
    /// Position of the item in the import file. For CSV file it will represent a line number, for JSON file it will represent an array index etc.
    #[serde(rename = "itemIndex", skip_serializing_if = "Option::is_none")]
    pub item_index: Option<i32>,
    /// Message describing the reason of import failure.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "x-class-name", skip_serializing_if = "Option::is_none")]
    pub x_class_name: Option<String>,
}

impl FailedItem {
    pub fn new() -> FailedItem {
        FailedItem {
            item: None,
            item_index: None,
            message: None,
            x_class_name: None,
        }
    }
}


