/*
 * List Type
 *
 * A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'om.liferay.headless.admin.list.type.client', and version '1.0.0'.. A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.headless.admin.list.type.client', and version '1.0.11'.
 *
 * The version of the OpenAPI document: v1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use headless_common::convert_case::Casing;
use headless_common::{convert_case::Case, field_types::FieldName};
use std::fmt::Display;

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, FieldName)]
pub struct ListTypeDefinition {
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions:
        Option<::std::collections::HashMap<String, ::std::collections::HashMap<String, String>>>,
    #[serde(rename = "dateCreated", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    #[serde(rename = "dateModified", skip_serializing_if = "Option::is_none")]
    pub date_modified: Option<String>,
    #[serde(
        rename = "externalReferenceCode",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_reference_code: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "listTypeEntries", skip_serializing_if = "Option::is_none")]
    pub list_type_entries: Option<Vec<crate::models::ListTypeEntry>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "name_i18n", skip_serializing_if = "Option::is_none")]
    pub name_i18n: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "x-class-name", skip_serializing_if = "Option::is_none")]
    pub x_class_name: Option<String>,
}

impl Display for ListTypeDefinitionFieldName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.name().to_case(Case::Camel))
    }
}

pub use ListTypeDefinitionFieldName as ListTypeDefinitionField;

impl ListTypeDefinition {
    pub fn new() -> ListTypeDefinition {
        ListTypeDefinition {
            actions: None,
            date_created: None,
            date_modified: None,
            external_reference_code: None,
            id: None,
            list_type_entries: None,
            name: None,
            name_i18n: None,
            x_class_name: None,
        }
    }
}
